sensors:
  - id: temp_sensor_1
    type: temperature
    sampling_rate: 5
    threshold: 50.0
  - id: temp_sensor_2
    type: temperature
    sampling_rate: 10
    threshold: 75.0
  - id: humidity_sensor_1
    type: humidity
    sampling_rate: 15
    threshold: 25.0
  - id: radio_sensor_1
    type: radio
    sampling_rate: 1
    threshold: -80.0
    custom_config:
      radio_config:
        frequency: 433.0
        modulation: "FSK"
        bandwidth: 125.0
        tx_power: 14.0
      mode: "receive"
