---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rust-sensor-nodes
spec:
  selector:
    matchLabels:
      app: rust-sensor-node
  template:
    metadata:
      labels:
        app: rust-sensor-node
    spec:
      containers:
        - name: rust-sensor-node
          image: rust_sensor_node:latest
          imagePullPolicy: Never
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZENOH_PEER
              value: "tcp/control-node-service:7447"
            - name: NUM_SENSORS
              value: "2"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - host1
                      - host2
                      - host3
                      - host4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-node
  template:
    metadata:
      labels:
        app: control-node
    spec:
      containers:
        - name: control-node
          image: rust_control_node:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7447
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/bin/config.yaml
              subPath: config.yaml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - host1 # Assuming host1 is your local machine
      volumes:
        - name: config-volume
          configMap:
            name: control-node-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: control-node-config
data:
  config.yaml: |
    sensors:
      host1-sensor-0:
        sampling_rate: 5
        threshold: 50.0
      host1-sensor-1:
        sampling_rate: 10
        threshold: 75.0
      host2-sensor-0:
        sampling_rate: 15
        threshold: 25.0
      host2-sensor-1:
        sampling_rate: 20
        threshold: 60.0
      host3-sensor-0:
        sampling_rate: 8
        threshold: 40.0
      host3-sensor-1:
        sampling_rate: 12
        threshold: 80.0
      host4-sensor-0:
        sampling_rate: 6
        threshold: 30.0
      host4-sensor-1:
        sampling_rate: 18
        threshold: 70.0
---
apiVersion: v1
kind: Service
metadata:
  name: control-node-service
spec:
  selector:
    app: control-node
  ports:
    - protocol: TCP
      port: 7447
      targetPort: 7447
