---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rust-sensor
spec:
  serviceName: "rust-sensor"
  replicas: 4
  selector:
    matchLabels:
      app: rust-sensor
  template:
    metadata:
      labels:
        app: rust-sensor
    spec:
      containers:
        - name: rust-sensor
          image: rust_sensor_node:latest
          imagePullPolicy: Never
          env:
            - name: SENSOR_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZENOH_PEER
              value: "tcp/control-node-service:7447"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: python-sensor
spec:
  serviceName: "python-sensor"
  replicas: 4
  selector:
    matchLabels:
      app: python-sensor
  template:
    metadata:
      labels:
        app: python-sensor
    spec:
      containers:
        - name: python-sensor
          image: python_sensor_node:latest
          imagePullPolicy: Never
          env:
            - name: SENSOR_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZENOH_PEER
              value: "tcp/control-node-service:7447"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-node-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-node-rust
  template:
    metadata:
      labels:
        app: control-node-rust
    spec:
      containers:
        - name: control-node-rust
          image: rust_control_node:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7447
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: control-node-config
---
apiVersion: v1
kind: Service
metadata:
  name: control-node-service
spec:
  selector:
    app: control-node-rust
  ports:
    - protocol: TCP
      port: 7447
      targetPort: 7447
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: control-node-config
data:
  config.yaml: |
    sensors:
      rust-sensor-0:
        sampling_rate: 5
        threshold: 50.0
      rust-sensor-1:
        sampling_rate: 10
        threshold: 75.0
      python-sensor-0:
        sampling_rate: 15
        threshold: 25.0
      python-sensor-1:
        sampling_rate: 20
        threshold: 100.0
