apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fabric-chart.fullname" . }}-rust-node
  labels:
    {{- include "fabric-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: rust-node
spec:
  replicas: {{ .Values.replicaCount.rustNode }}
  selector:
    matchLabels:
      {{- include "fabric-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rust-node
  template:
    metadata:
      labels:
        {{- include "fabric-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rust-node
    spec:
      containers:
        - name: {{ .Chart.Name }}-rust-node
          image: "{{ .Values.rustNode.image.repository }}:{{ .Values.rustNode.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rustNode.image.pullPolicy }}
          env:
            - name: RUST_LOG
              value: "info"
            - name: QUADCOPTER_ID
              value: {{ printf "rust-quadcopter-%s" (randAlphaNum 8 | lower) | quote }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "export QUADCOPTER_ID=quadcopter-rust-$(hostname | cut -d'-' -f3-)"]
          ports:
            - name: http
              containerPort: 7447
              protocol: TCP
          resources:
            {{- toYaml .Values.rustNode.resources | nindent 12 }}
