apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-orchestrator
  labels:
    {{- include "fabric-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.rustOrchestrator }}
  selector:
    matchLabels:
      {{- include "fabric-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rust-orchestrator
  template:
    metadata:
      labels:
        {{- include "fabric-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rust-orchestrator
    spec:
      containers:
        - name: rust-orchestrator
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/rust_orchestrator:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RUST_LOG
              value: "info"
          ports:
            - name: http
              containerPort: 7447
              protocol: TCP
          resources:
            {{- toYaml .Values.rustOrchestrator.resources | nindent 12 }}
