# Default values for fabric-chart
replicaCount:
  rustNode: 2
  pythonNode: 2
  rustOrchestrator: 1

image:
  registry: k3d-registry.localhost:5001
  repository: varunkamath/fabric
  pullPolicy: IfNotPresent
  tag: "latest"

rustNode:
  image:
    repository: k3d-registry.localhost:5001/varunkamath/fabric-rust-node
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

pythonNode:
  image:
    repository: k3d-registry.localhost:5001/varunkamath/fabric-python-node
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

rustOrchestrator:
  image:
    repository: k3d-registry.localhost:5001/varunkamath/fabric-rust-orchestrator
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

orchestrator:
  image:
    repository: k3d-registry.localhost:5001/varunkamath/fabric-orchestrator
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

service:
  type: ClusterIP
  port: 7447

ingress:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
