# Default values for fabric-chart
replicaCount:
  rustNode: 2
  pythonNode: 2
  rustOrchestrator: 1

image:
  registry: k3d-registry.localhost:5001
  repository: varunkamath/fabric
  pullPolicy: IfNotPresent
  tag: "latest"

rustNode:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
      ephemeral-storage: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 500Mi

pythonNode:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
      ephemeral-storage: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 500Mi

rustOrchestrator:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 2Gi
    requests:
      cpu: 250m
      memory: 256Mi
      ephemeral-storage: 1Gi

service:
  type: ClusterIP
  port: 7447

ingress:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
