name: Build and test all components

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Add this line to enable manual triggers

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (
        contains(github.event.head_commit.modified, 'rust/') ||
        contains(github.event.head_commit.modified, 'Cargo.toml') ||
        contains(github.event.head_commit.modified, 'Cargo.lock') ||
        contains(github.event.head_commit.modified, '.github/workflows/main.yml')
      )
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup toolchain install stable --profile minimal

      - name: Lint Rust code
        run: cargo clippy -- -D warnings

      - name: Run Rust tests
        run: cargo test

  python-ci:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (
        contains(github.event.head_commit.modified, 'python/') ||
        contains(github.event.head_commit.modified, '.github/workflows/main.yml')
      )
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-asyncio
          pip install -r python/sensor_node/requirements.txt
          pip install -r python/control_node/requirements.txt

      - name: Lint Python code
        run: ruff check .

      - name: Check Python file structure
        run: |
          echo "Directory structure:"
          tree python
          echo "Checking for test files:"
          ls -l python/sensor_node/test_sensor_node.py
          ls -l python/control_node/test_control_node.py

      - name: Run Python tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest -v python/sensor_node/test_sensor_node.py
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest -v python/control_node/test_control_node.py
