name: CI / CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add rustfmt clippy

      - name: Format Rust code
        run: cargo fmt --all -- --check

      - name: Lint Rust code
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build Rust library
        run: cargo build --verbose

      - name: Run Rust tests
        run: cargo test --verbose

  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-asyncio
          pip install -r python/sensor_node/requirements.txt
          pip install -r python/control_node/requirements.txt

      - name: Lint Python code
        run: ruff check .

      - name: Check Python file structure
        run: |
          echo "Directory structure:"
          tree python
          echo "Checking for test files:"
          ls -l python/sensor_node/test_sensor_node.py
          ls -l python/control_node/test_control_node.py

      - name: Run Python tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest -v python/sensor_node/test_sensor_node.py
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest -v python/control_node/test_control_node.py
