name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.modified, 'Dockerfile') &&
      (
        contains(github.event.head_commit.modified, 'python/') ||
        contains(github.event.head_commit.modified, 'rust/') ||
        contains(github.event.head_commit.modified, 'Cargo.toml') ||
        contains(github.event.head_commit.modified, 'Cargo.lock') ||
        contains(github.event.head_commit.modified, '.github/workflows/main.yml')
      )
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-asyncio
          pip install -r python/sensor_node/requirements.txt
          pip install -r python/control_node/requirements.txt

      - name: Lint Python code
        run: ruff check .

      - name: Set up Rust
        run: rustup toolchain install stable --profile minimal

      - name: Lint Rust code
        run: cargo clippy -- -D warnings

      - name: Run Rust tests
        run: cargo test

      - name: Check Python file structure
        run: |
          echo "Directory structure:"
          tree python
          echo "Checking for test files:"
          ls -l python/sensor_node/test_sensor_node.py
          ls -l python/control_node/test_control_node.py

      - name: Run Python tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest -v python/sensor_node/test_sensor_node.py
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest -v python/control_node/test_control_node.py

  build-docker:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.modified, 'Dockerfile') ||
      contains(github.event.head_commit.modified, 'python/') ||
      contains(github.event.head_commit.modified, 'rust/') ||
      contains(github.event.head_commit.modified, 'Cargo.toml') ||
      contains(github.event.head_commit.modified, 'Cargo.lock') ||
      contains(github.event.head_commit.modified, '.github/workflows/main.yml')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Print directory structure
        run: |
          pwd
          ls -R

      - name: Build Rust sensor node
        run: |
          docker build -t rust_sensor_node_dependencies:latest -f rust/docker/sensor_dependencies.Dockerfile .
          docker build -t rust_sensor_node:latest -f rust/docker/sensor_package.Dockerfile .

      - name: Build Python sensor node
        run: |
          docker build -t python_sensor_node_dependencies:latest -f python/docker/sensor_dependencies.Dockerfile .
          docker build -t python_sensor_node:latest -f python/docker/sensor_package.Dockerfile .

      - name: Build Rust control node
        run: |
          docker build -t rust_control_node_dependencies:latest -f rust/docker/control_dependencies.Dockerfile .
          docker build -t rust_control_node:latest -f rust/docker/control_package.Dockerfile .

      - name: Build Python control node
        run: |
          docker build -t python_control_node_dependencies:latest -f python/docker/control_dependencies.Dockerfile .
          docker build -t python_control_node:latest -f python/docker/control_package.Dockerfile .
